### ISSUE TITLE
Adding Pyfhel to the runtime

### ISSUE THREAD

**Issue by andreweland** [drivendataorg/pets-prize-challenge-runtime#4]
[We'd](https://diagonal.works/) like to add [Pyfhel](https://pyfhel.readthedocs.io/en/latest/) to the runtime, to support the use of homomorphic encryption in our entry. It's only available as a source package on PyPI (and not at all via anaconda), and the runtime image doesn't currently include the tools necessary to build from c++ source. Rather than adding those tools to the image, I think it's probably most pragmatic to install via a pre-built wheel that's added to this repo. We could do this and submit via a pull request, but for binary provenance I assume you'd want to do this yourselves - maybe tracking the build itself in a different repo. We're happy to help out if you have approaches that make sense to you - let us know!

**Comment by jayqi** [comment]
Hi @andreweland,

More information would be great. I think either building as part of the runtime image build or including as a pre-built wheel are both possible options.

Can you provide more information or link to other references regarding the prerequisites for building the library? The [installation page in the official docs](https://pyfhel.readthedocs.io/en/latest/source/getting_started/1_installation.html) is pretty minimal.

**Comment by andreweland** [comment]
Hi @jayqi - I've added [scripts to build Pyhfel](https://github.com/diagonalworks/diagonal-pets/tree/main/deps/pyfhel) in a version of the runtime image that's been extended with compilation tools. I've also added the [binary wheel built this way as a release artifact](https://github.com/diagonalworks/diagonal-pets/releases/tag/build-pyfhel). Does that give you enough to work with?

**Comment by jayqi** [comment]
Hi @andreweland,

I've opted to just build Pyfhel as part of the image build. Currently, the version is pinned to the head commit of Pyfhel's master branch in order to take advantage of the fix for https://github.com/ibarrond/Pyfhel/issues/167 – if that change gets released to PyPI then we may swap over to the PyPI stable version.
