### ISSUE TITLE
pets-prize-challenge phase-2 datasets

### ISSUE THREAD

**Issue by little12** [drivendataorg/pets-prize-challenge-runtime#41]
hello, i want to know where can i get the datasets of PETS? to do some practice, to prepare for  competition of next year.
such as swift and bank data.

**Comment by jayqi** [comment]
Please see here: https://community.drivendata.org/t/pets-challenge-data-availability/7877/23?u=jayqi

**Comment by little12** [comment]
> Please see here: https://community.drivendata.org/t/pets-challenge-data-availability/7877/23?u=jayqi

thanks
